### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'get'

### ISSUE THREAD

**Issue by jag-k** [yunstanford/jinja2-sanic#3]
Then i'm using template

```
[2020-06-04 19:44:25 +0300] [76698] [ERROR] Exception occurred while handling uri: 'https://0.0.0.0/register'
Traceback (most recent call last):
  File "/Users/jagk/Projects/Python/1000listnick-it/venv/lib/python3.8/site-packages/sanic/app.py", line 973, in handle_request
    response = await response
  File "/Users/jagk/Projects/Python/1000listnick-it/venv/lib/python3.8/site-packages/jinja2_sanic/__init__.py", line 164, in wrapped
    return render_template(template_name, request, context,
  File "/Users/jagk/Projects/Python/1000listnick-it/venv/lib/python3.8/site-packages/jinja2_sanic/__init__.py", line 122, in render_template
    text = render_string(template_name, request, context, app_key=app_key)
  File "/Users/jagk/Projects/Python/1000listnick-it/venv/lib/python3.8/site-packages/jinja2_sanic/__init__.py", line 98, in render_string
    if request.get(REQUEST_CONTEXT_KEY):
AttributeError: 'Request' object has no attribute 'get'
```

**Comment by jag-k** [comment]
This problem on Sanic v20.3.0
On Sanic v19.12.2 all ok
